let structureList=[
    {
        id: "sheep",
        requiring : "wheat",
        earning : 20,
        startX : 1,
        startY : 2,
        sizeX : 2,
        sizeY : 1,
        willAddContent : false,
        canBeBoughtFromShop :false,
    },
    {
        id : "cow",
        requiring : "corn",
        earning :30,
        startX : 3,
        startY : 2,
        sizeX : 2,
        sizeY : 1,
        willAddContent : true,
        contentAdded : 'milk',
        canBeBoughtFromShop : true,
    },
    {
        id : "chicken",
        requiring : "fiber",
        earning : 50,
        startX : 5.5,
        startY : 2,
        sizeX : 1,
        sizeY : 1,
        willAddContent : true,
        contentAdded : 'largeEgg',
        canBeBoughtFromShop : true,
    },
    {
        id : "rabbit",
        requiring : "radish",
        earning : 100,
        startX : 7,
        startY : 2,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
    {
        id : "pig",
        requiring : "apple",
        earning : 200,
        startX : 9,
        startY : 2,
        willAddContent : true,
        contentAdded : 'truffle',
        canBeBoughtFromShop : true,
    },
    {
        id : "horse",
        requiring : "milk",
        earning : 250,
        startX : 1,
        startY : 11,
        willAddContent : true,
        contentAdded : 'flower',
        canBeBoughtFromShop : true,
    },
    {
        id : "mayonnaiseMachine",
        requiring : "largeEgg",
        earning: 750,
        startX: 1,
        startY: 5,
        willAddContent: true,
        contentAdded : 'mayonnaise',
        canBeBoughtFromShop : true, 
    },
    {
        id : "loom",
        requiring : 'wool',
        earning : 200,
        startX : 3,
        startY : 5,
        willAddContent : true,
        contentAdded : 'cloth',
        canBeBoughtFromShop : true,
    },
    {
        id : "smileEggPress" ,
        requiring : "smile",
        earning : 200,
        startX : 5,
        startY : 5,
        willAddContent : true,
        contentAdded : 'smile',
        canBeBoughtFromShop : true,
    },
    {
        id : "oilMaker",
        requiring : "truffle",
        earning : 500,
        startX : 7,
        startY : 5,
        willAddContent : true,
        contentAdded : 'oil',
        canBeBoughtFromShop : true,
    },
    {
        id : "beeHouse",
        requiring : "flower",
        earning : 250,
        startX : 9,
        startY : 5,
        willAddContent : true,
        contentAdded : 'honey',
        canBeBoughtFromShop : true,
    },
    {
        id : "bear",
        requiring : "honey",
        earning : 500,
        startX : 1,
        startY : 8,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
    {
        id : "dinosaur",
        requiring : "largeEgg",
        earning : 1000,
        startX : 4,
        startY : 9,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
    {
        id : "ostrich",
        requiring : "sardine",
        earning : 1200,
        startX : 6,
        startY : 8,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
    {
        id : "wolf",
        requiring : "oil",
        earning : 1500,
        startX : 9,
        startY : 8,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
    {
        id : "fox",
        requiring : "truffle",
        earning : 2000,
        startX : 4,
        startY : 10.5,
        willAddContent : true,
        contentAdded : 'ring',
        canBeBoughtFromShop : true,
    },
    {
        id : "ikun",
        requiring : "ring",
        earning : 2500,
        startX : 6,
        startY : 11.5,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
    {
        id : "kunkun",
        requiring : "smile",
        earning : 3000,
        startX : 8,
        startY : 11.5,
        willAddContent : false,
        canBeBoughtFromShop : true,
    },
];
export{structureList}
